# Generated by Django 2.2.17 on 2020-12-20 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_loginotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginotp',
            name='email_sid',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='loginotp',
            name='phone_sid',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='loginotp',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('canceled', 'Canceled')], default='pending', max_length=10),
        ),
    ]
