# Generated by Django 2.2.17 on 2020-12-20 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201220_1350'),
        ('users', '0005_userprofile_gender'),
    ]

    operations = [
    ]
