# Generated by Django 2.2.17 on 2020-12-21 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_merge_20201220_1126'),
        ('users', '0008_auto_20201221_1010'),
    ]

    operations = [
    ]
