# Generated by Django 2.2.17 on 2020-12-24 06:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201223_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='acuity_form_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True),
        ),
    ]
