# Generated by Django 2.2.17 on 2020-12-27 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golab', '0013_delete_patientnotification'),
        ('users', '0012_patientnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientnotification',
            name='acuity_appointment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='golab.AcuityAppointment'),
        ),
    ]
