# Generated by Django 2.2.17 on 2021-01-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210104_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginotp',
            name='otp_hash',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
    ]
