# Generated by Django 2.2.17 on 2021-01-07 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210104_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientnotification',
            name='email_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientnotification',
            name='sms_status',
            field=models.BooleanField(default=False),
        ),
    ]
