# Generated by Django 2.2.17 on 2021-01-14 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_patientnotification_twilio_sms_sid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientnotification',
            name='sms_status',
        ),
    ]
