# Generated by Django 2.2.17 on 2021-01-21 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_patientnotification_sms_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientnotification',
            options={'ordering': ('-updated',), 'verbose_name': 'Patient Notification', 'verbose_name_plural': 'Patient Notifications'},
        ),
    ]
