# Generated by Django 2.2.17 on 2020-12-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golab', '0003_test_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactSheetUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet', models.FileField(blank=True, null=True, upload_to='fact_sheets', verbose_name='Select File')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fact Sheet Upload',
                'verbose_name_plural': 'Fact Sheet Upload',
                'ordering': ('-created',),
            },
        ),
    ]
