# Generated by Django 2.2.17 on 2020-12-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golab', '0005_acuityappointment_appointment_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acuityappointment',
            name='acuity_appointment_id',
            field=models.BigIntegerField(default=None, unique=True, verbose_name='Acuity Appointment ID'),
        ),
    ]
