# Generated by Django 2.2.17 on 2020-12-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golab', '0005_auto_20201223_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='result',
            field=models.CharField(blank=True, choices=[('DETECTED', 'DETECTED'), ('NOT DETECTED', 'NOT DETECTED')], max_length=15, null=True, verbose_name='Results'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_status',
            field=models.CharField(blank=True, choices=[('Check In', 'Check In'), ('Sample collected - swab has been performed', 'Sample collected - swab has been performed'), ('Sample Processing', 'Sample Processing'), ('Results ready', 'Results ready')], max_length=50, null=True, verbose_name='Test Status'),
        ),
    ]
