# Generated by Django 2.2.17 on 2020-12-24 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golab', '0006_auto_20201223_2132'),
        ('golab', '0006_auto_20201223_1325'),
    ]

    operations = [
    ]
