# Generated by Django 2.2.17 on 2020-12-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golab', '0008_auto_20201224_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='specimen_type',
            field=models.CharField(blank=True, choices=[('Nasopharyngeal Swab', 'Nasopharyngeal Swab'), ('Nasal Swab', 'Nasal Swab'), ('Throat Swab', 'Throat Swab')], max_length=255, null=True, verbose_name='Specimen Type'),
        ),
    ]
