# Generated by Django 2.2.17 on 2020-12-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golab', '0009_auto_20201227_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_status',
            field=models.CharField(blank=True, choices=[('check_in', 'Check In'), ('collected', 'Sample collected - swab has been performed'), ('processing', 'Sample Processing'), ('ready', 'Results ready')], default=None, max_length=50, null=True, verbose_name='Test Status'),
        ),
    ]
