# Generated by Django 2.2.17 on 2020-12-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golab', '0010_auto_20201227_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='result',
            field=models.CharField(blank=True, choices=[('detected', 'DETECTED'), ('not_detected', 'NOT DETECTED')], default=None, max_length=15, null=True, verbose_name='Results'),
        ),
        migrations.AlterField(
            model_name='test',
            name='specimen_type',
            field=models.CharField(blank=True, choices=[('nasopharyngeal_swab', 'Nasopharyngeal Swab'), ('nasal_swab', 'Nasal Swab'), ('throat_swab', 'Throat Swab')], default=None, max_length=255, null=True, verbose_name='Specimen Type'),
        ),
    ]
