# Generated by Django 2.2.17 on 2020-12-27 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golab', '0012_patientnotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientNotification',
        ),
    ]
