# Generated by Django 2.2.17 on 2020-12-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golab', '0013_delete_patientnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='acuityappointment',
            name='appointment_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Appointment Type'),
        ),
    ]
