# Generated by Django 2.2.17 on 2020-12-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golab', '0013_delete_patientnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='acuityappointment',
            name='send_sms_notification',
            field=models.BooleanField(default=True),
        ),
    ]
