# Generated by Django 2.2.17 on 2020-12-28 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golab', '0014_acuityappointment_send_sms_notification'),
        # ('golab', '0015_populate_appointment_type1'),
    ]

    operations = [
    ]
