# Generated by Django 2.2.17 on 2020-12-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golab', '0016_merge_20201228_1252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ('-created',), 'verbose_name': 'Test Result', 'verbose_name_plural': 'Test Results'},
        ),
        migrations.AlterField(
            model_name='test',
            name='result',
            field=models.CharField(blank=True, choices=[('DETECTED', 'DETECTED'), ('NOT DETECTED', 'NOT DETECTED')], max_length=15, null=True, verbose_name='Results'),
        ),
        migrations.AlterField(
            model_name='test',
            name='specimen_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Specimen Type'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_status',
            field=models.CharField(blank=True, choices=[('Check In', 'Check In'), ('Sample collected - swab has been performed', 'Sample collected - swab has been performed'), ('Sample Processing', 'Sample Processing'), ('Results ready', 'Results ready')], max_length=50, null=True, verbose_name='Test Status'),
        ),
    ]
