# Generated by Django 2.2.17 on 2020-12-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golab', '0017_auto_20201228_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='result',
            field=models.CharField(blank=True, choices=[('detected', 'DETECTED'), ('not_detected', 'NOT DETECTED')], default=None, max_length=15, null=True, verbose_name='Results'),
        ),
        migrations.AlterField(
            model_name='test',
            name='specimen_type',
            field=models.CharField(blank=True, choices=[('nasopharyngeal_swab', 'Nasopharyngeal Swab'), ('nasal_swab', 'Nasal Swab'), ('throat_swab', 'Throat Swab')], default=None, max_length=255, null=True, verbose_name='Specimen Type'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_status',
            field=models.CharField(blank=True, choices=[('check_in', 'Check In'), ('collected', 'Sample collected - swab has been performed'), ('processing', 'Sample Processing'), ('ready', 'Results ready')], max_length=50, null=True, verbose_name='Test Status'),
        ),
    ]
