# Generated by Django 2.2.17 on 2020-12-31 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golab', '0018_auto_20201228_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_status',
            field=models.CharField(blank=True, choices=[('check_in', 'Checked In'), ('collected', 'Sample collected - swab has been performed'), ('processing', 'Sample Processing'), ('ready', 'Results ready')], max_length=50, null=True, verbose_name='Test Status'),
        ),
    ]
