# Generated by Django 2.2.17 on 2020-12-31 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golab', '0018_auto_20201228_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='processed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
