# Generated by Django 2.2.17 on 2020-12-31 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golab', '0019_test_processed_date'),
        ('golab', '0019_auto_20201231_0327'),
    ]

    operations = [
    ]
