# Generated by Django 2.2.17 on 2021-01-14 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golab', '0015_populate_appointment_type1'),
        ('golab', '0020_merge_20201231_2244'),
    ]

    operations = [
    ]
