# Generated by Django 2.2.17 on 2021-02-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golab', '0022_testtype_fact_sheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='acuityappointment',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='acuityappointment',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Last Name'),
        ),
    ]
