# Generated by Django 2.2.17 on 2021-02-26 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golab', '0023_auto_20210205_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='processed_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
