# Generated by Django 2.2.17 on 2021-04-08 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golab', '0024_auto_20210226_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='acuity_appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actuity_appointment_test', to='golab.AcuityAppointment'),
        ),
    ]
